[package]
name = "kg-display-derive"
version = "0.1.1"
authors = ["Jakub Chłapiński <jakub.chlapinski@kodegenix.pl>"]
description = """
Macro implementation for #[derive(Display)].
"""
readme = "README.md"
license = "Apache-2.0 OR MIT"
repository = "https://github.com/Kodegenix/kg-display"
workspace = ".."
edition = "2018"

[lib]
proc-macro = true

[dependencies]
kg-display = { path = "../kg-display" }
kg-utils = "0.2.4"
proc-macro2 = { version = "0.4.30", features = ["nightly"] }
quote = "0.6.12"
syn = { version = "0.15.39", features = ["full"] }
synstructure = "0.11.0"
