[package]
name = "kg-display-derive"
version = "0.1.0"
authors = ["Jakub Chłapiński <jakub.chlapinski@kodegenix.pl>"]
description = """
Macro implementation for #[derive(Display)].
"""
readme = "README.md"
license = "Apache-2.0 OR MIT"
repository = "https://github.com/Kodegenix/kg-display"
workspace = ".."
edition = "2018"

[lib]
proc-macro = true

[dependencies]
kg-display = { version = "0.1", path = "../kg-display" }
kg-utils = "0.2"
proc-macro2 = { version = "0.4", features = ["nightly"] }
quote = "0.6"
syn = { version = "0.15", features = ["full"] }
synstructure = "0.10"
